CREATE TABLE [dbo].[Data_Pipeline_Lineage] (

	[Lineage_ID] varchar(100) NOT NULL, 
	[Trigger_Name] varchar(500) NULL, 
	[Table_ID] int NULL, 
	[Source_Entity] varchar(4000) NULL, 
	[Source_Datastore] varchar(4000) NULL, 
	[Source_Medallion_Layer] varchar(50) NULL, 
	[Source_Type] varchar(100) NULL, 
	[Source_Workspace_Name] varchar(500) NULL, 
	[Source_ABFSS_Path] varchar(2000) NULL, 
	[Source_Connection_ID] varchar(100) NULL, 
	[Target_Entity] varchar(4000) NULL, 
	[Target_Datastore] varchar(4000) NULL, 
	[Target_Medallion_Layer] varchar(50) NULL, 
	[Target_Type] varchar(100) NULL, 
	[Target_Workspace_Name] varchar(500) NULL, 
	[Target_ABFSS_Path] varchar(2000) NULL, 
	[Relationship_Type] varchar(100) NULL, 
	[Transformation_Applied] varchar(4000) NULL, 
	[Lineage_Depth] int NULL, 
	[Lineage_Path] varchar(8000) NULL, 
	[Is_Cross_Trigger] bit NULL, 
	[Cross_Trigger_Dependencies] varchar(1000) NULL, 
	[Lineage_Summary] varchar(1000) NULL, 
	[Source_Lineage_Narrative] varchar(max) NULL, 
	[Target_Lineage_Narrative] varchar(max) NULL, 
	[Lineage_Generated_At] datetime2(6) NULL, 
	[Lineage_Version] int NULL, 
	[Date_Key] int NULL
);